// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lightsparkdev/spark/so/ent/predicate"
	"github.com/lightsparkdev/spark/so/ent/signingcommitment"
)

// SigningCommitmentDelete is the builder for deleting a SigningCommitment entity.
type SigningCommitmentDelete struct {
	config
	hooks    []Hook
	mutation *SigningCommitmentMutation
}

// Where appends a list predicates to the SigningCommitmentDelete builder.
func (scd *SigningCommitmentDelete) Where(ps ...predicate.SigningCommitment) *SigningCommitmentDelete {
	scd.mutation.Where(ps...)
	return scd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (scd *SigningCommitmentDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, scd.sqlExec, scd.mutation, scd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (scd *SigningCommitmentDelete) ExecX(ctx context.Context) int {
	n, err := scd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (scd *SigningCommitmentDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(signingcommitment.Table, sqlgraph.NewFieldSpec(signingcommitment.FieldID, field.TypeUUID))
	if ps := scd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, scd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	scd.mutation.done = true
	return affected, err
}

// SigningCommitmentDeleteOne is the builder for deleting a single SigningCommitment entity.
type SigningCommitmentDeleteOne struct {
	scd *SigningCommitmentDelete
}

// Where appends a list predicates to the SigningCommitmentDelete builder.
func (scdo *SigningCommitmentDeleteOne) Where(ps ...predicate.SigningCommitment) *SigningCommitmentDeleteOne {
	scdo.scd.mutation.Where(ps...)
	return scdo
}

// Exec executes the deletion query.
func (scdo *SigningCommitmentDeleteOne) Exec(ctx context.Context) error {
	n, err := scdo.scd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{signingcommitment.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (scdo *SigningCommitmentDeleteOne) ExecX(ctx context.Context) {
	if err := scdo.Exec(ctx); err != nil {
		panic(err)
	}
}
