// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lightsparkdev/spark/so/ent/predicate"
	"github.com/lightsparkdev/spark/so/ent/tokentransactionpeersignature"
)

// TokenTransactionPeerSignatureDelete is the builder for deleting a TokenTransactionPeerSignature entity.
type TokenTransactionPeerSignatureDelete struct {
	config
	hooks    []Hook
	mutation *TokenTransactionPeerSignatureMutation
}

// Where appends a list predicates to the TokenTransactionPeerSignatureDelete builder.
func (ttpsd *TokenTransactionPeerSignatureDelete) Where(ps ...predicate.TokenTransactionPeerSignature) *TokenTransactionPeerSignatureDelete {
	ttpsd.mutation.Where(ps...)
	return ttpsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ttpsd *TokenTransactionPeerSignatureDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ttpsd.sqlExec, ttpsd.mutation, ttpsd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ttpsd *TokenTransactionPeerSignatureDelete) ExecX(ctx context.Context) int {
	n, err := ttpsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ttpsd *TokenTransactionPeerSignatureDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(tokentransactionpeersignature.Table, sqlgraph.NewFieldSpec(tokentransactionpeersignature.FieldID, field.TypeUUID))
	if ps := ttpsd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ttpsd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ttpsd.mutation.done = true
	return affected, err
}

// TokenTransactionPeerSignatureDeleteOne is the builder for deleting a single TokenTransactionPeerSignature entity.
type TokenTransactionPeerSignatureDeleteOne struct {
	ttpsd *TokenTransactionPeerSignatureDelete
}

// Where appends a list predicates to the TokenTransactionPeerSignatureDelete builder.
func (ttpsdo *TokenTransactionPeerSignatureDeleteOne) Where(ps ...predicate.TokenTransactionPeerSignature) *TokenTransactionPeerSignatureDeleteOne {
	ttpsdo.ttpsd.mutation.Where(ps...)
	return ttpsdo
}

// Exec executes the deletion query.
func (ttpsdo *TokenTransactionPeerSignatureDeleteOne) Exec(ctx context.Context) error {
	n, err := ttpsdo.ttpsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{tokentransactionpeersignature.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ttpsdo *TokenTransactionPeerSignatureDeleteOne) ExecX(ctx context.Context) {
	if err := ttpsdo.Exec(ctx); err != nil {
		panic(err)
	}
}
