config:
  target: "http://localhost"
  engines:
    spark: {}
  phases:
    - duration: 2
      arrivalRate: 10
      maxVusers: 10

scenarios:
  - name: "Fund Wallet Pool"
    weight: 1
    engine: spark
    before:
      # Initialize distributor pool
      - initializePools:
          pools:
            - name: "distributor-pool"
              amount: 20
              randomSelection: true
              batchSize: 20
              mnemonicsFile: "./mnemonics/batch-source-wallets.txt"
              lockWallets: true

    flow:
      - loop:
          count: 4
          actions:
            - fundWalletPool:
                pools: ["distributor-pool"]
                minAmount: 5000

    after:
      - cleanupPools: {}
