// Code generated by ent, DO NOT EDIT.

package tokenpartialrevocationsecretshare

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the tokenpartialrevocationsecretshare type in the database.
	Label = "token_partial_revocation_secret_share"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldOperatorIdentityPublicKey holds the string denoting the operator_identity_public_key field in the database.
	FieldOperatorIdentityPublicKey = "operator_identity_public_key"
	// FieldSecretShare holds the string denoting the secret_share field in the database.
	FieldSecretShare = "secret_share"
	// EdgeTokenOutput holds the string denoting the token_output edge name in mutations.
	EdgeTokenOutput = "token_output"
	// Table holds the table name of the tokenpartialrevocationsecretshare in the database.
	Table = "token_partial_revocation_secret_shares"
	// TokenOutputTable is the table that holds the token_output relation/edge.
	TokenOutputTable = "token_partial_revocation_secret_shares"
	// TokenOutputInverseTable is the table name for the TokenOutput entity.
	// It exists in this package in order to avoid circular dependency with the "tokenoutput" package.
	TokenOutputInverseTable = "token_outputs"
	// TokenOutputColumn is the table column denoting the token_output relation/edge.
	TokenOutputColumn = "token_output_token_partial_revocation_secret_shares"
)

// Columns holds all SQL columns for tokenpartialrevocationsecretshare fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldOperatorIdentityPublicKey,
	FieldSecretShare,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "token_partial_revocation_secret_shares"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"token_output_token_partial_revocation_secret_shares",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/lightsparkdev/spark/so/ent/runtime"
var (
	Hooks [1]ent.Hook
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// SecretShareValidator is a validator for the "secret_share" field. It is called by the builders before save.
	SecretShareValidator func([]byte) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the TokenPartialRevocationSecretShare queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByTokenOutputField orders the results by token_output field.
func ByTokenOutputField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTokenOutputStep(), sql.OrderByField(field, opts...))
	}
}
func newTokenOutputStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TokenOutputInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TokenOutputTable, TokenOutputColumn),
	)
}
