// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: mock.proto

package mock

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InterruptTransferRequest_InterruptTransferAction int32

const (
	InterruptTransferRequest_NONE      InterruptTransferRequest_InterruptTransferAction = 0
	InterruptTransferRequest_INTERRUPT InterruptTransferRequest_InterruptTransferAction = 1
	InterruptTransferRequest_RESUME    InterruptTransferRequest_InterruptTransferAction = 2
)

// Enum value maps for InterruptTransferRequest_InterruptTransferAction.
var (
	InterruptTransferRequest_InterruptTransferAction_name = map[int32]string{
		0: "NONE",
		1: "INTERRUPT",
		2: "RESUME",
	}
	InterruptTransferRequest_InterruptTransferAction_value = map[string]int32{
		"NONE":      0,
		"INTERRUPT": 1,
		"RESUME":    2,
	}
)

func (x InterruptTransferRequest_InterruptTransferAction) Enum() *InterruptTransferRequest_InterruptTransferAction {
	p := new(InterruptTransferRequest_InterruptTransferAction)
	*p = x
	return p
}

func (x InterruptTransferRequest_InterruptTransferAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InterruptTransferRequest_InterruptTransferAction) Descriptor() protoreflect.EnumDescriptor {
	return file_mock_proto_enumTypes[0].Descriptor()
}

func (InterruptTransferRequest_InterruptTransferAction) Type() protoreflect.EnumType {
	return &file_mock_proto_enumTypes[0]
}

func (x InterruptTransferRequest_InterruptTransferAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InterruptTransferRequest_InterruptTransferAction.Descriptor instead.
func (InterruptTransferRequest_InterruptTransferAction) EnumDescriptor() ([]byte, []int) {
	return file_mock_proto_rawDescGZIP(), []int{1, 0}
}

type InterruptCoopExitRequest_InterruptCoopExitAction int32

const (
	InterruptCoopExitRequest_NONE      InterruptCoopExitRequest_InterruptCoopExitAction = 0
	InterruptCoopExitRequest_INTERRUPT InterruptCoopExitRequest_InterruptCoopExitAction = 1
	InterruptCoopExitRequest_RESUME    InterruptCoopExitRequest_InterruptCoopExitAction = 2
)

// Enum value maps for InterruptCoopExitRequest_InterruptCoopExitAction.
var (
	InterruptCoopExitRequest_InterruptCoopExitAction_name = map[int32]string{
		0: "NONE",
		1: "INTERRUPT",
		2: "RESUME",
	}
	InterruptCoopExitRequest_InterruptCoopExitAction_value = map[string]int32{
		"NONE":      0,
		"INTERRUPT": 1,
		"RESUME":    2,
	}
)

func (x InterruptCoopExitRequest_InterruptCoopExitAction) Enum() *InterruptCoopExitRequest_InterruptCoopExitAction {
	p := new(InterruptCoopExitRequest_InterruptCoopExitAction)
	*p = x
	return p
}

func (x InterruptCoopExitRequest_InterruptCoopExitAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InterruptCoopExitRequest_InterruptCoopExitAction) Descriptor() protoreflect.EnumDescriptor {
	return file_mock_proto_enumTypes[1].Descriptor()
}

func (InterruptCoopExitRequest_InterruptCoopExitAction) Type() protoreflect.EnumType {
	return &file_mock_proto_enumTypes[1]
}

func (x InterruptCoopExitRequest_InterruptCoopExitAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InterruptCoopExitRequest_InterruptCoopExitAction.Descriptor instead.
func (InterruptCoopExitRequest_InterruptCoopExitAction) EnumDescriptor() ([]byte, []int) {
	return file_mock_proto_rawDescGZIP(), []int{4, 0}
}

type CleanUpPreimageShareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentHash   []byte                 `protobuf:"bytes,1,opt,name=payment_hash,json=paymentHash,proto3" json:"payment_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanUpPreimageShareRequest) Reset() {
	*x = CleanUpPreimageShareRequest{}
	mi := &file_mock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanUpPreimageShareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanUpPreimageShareRequest) ProtoMessage() {}

func (x *CleanUpPreimageShareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanUpPreimageShareRequest.ProtoReflect.Descriptor instead.
func (*CleanUpPreimageShareRequest) Descriptor() ([]byte, []int) {
	return file_mock_proto_rawDescGZIP(), []int{0}
}

func (x *CleanUpPreimageShareRequest) GetPaymentHash() []byte {
	if x != nil {
		return x.PaymentHash
	}
	return nil
}

type InterruptTransferRequest struct {
	state         protoimpl.MessageState                           `protogen:"open.v1"`
	Action        InterruptTransferRequest_InterruptTransferAction `protobuf:"varint,1,opt,name=action,proto3,enum=mock.InterruptTransferRequest_InterruptTransferAction" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterruptTransferRequest) Reset() {
	*x = InterruptTransferRequest{}
	mi := &file_mock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterruptTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterruptTransferRequest) ProtoMessage() {}

func (x *InterruptTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterruptTransferRequest.ProtoReflect.Descriptor instead.
func (*InterruptTransferRequest) Descriptor() ([]byte, []int) {
	return file_mock_proto_rawDescGZIP(), []int{1}
}

func (x *InterruptTransferRequest) GetAction() InterruptTransferRequest_InterruptTransferAction {
	if x != nil {
		return x.Action
	}
	return InterruptTransferRequest_NONE
}

type UpdateNodesStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeIds       []string               `protobuf:"bytes,1,rep,name=node_ids,json=nodeIds,proto3" json:"node_ids,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNodesStatusRequest) Reset() {
	*x = UpdateNodesStatusRequest{}
	mi := &file_mock_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNodesStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNodesStatusRequest) ProtoMessage() {}

func (x *UpdateNodesStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mock_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNodesStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateNodesStatusRequest) Descriptor() ([]byte, []int) {
	return file_mock_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateNodesStatusRequest) GetNodeIds() []string {
	if x != nil {
		return x.NodeIds
	}
	return nil
}

func (x *UpdateNodesStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// TriggerTaskRequest is used to trigger a scheduled task immediately in hermetic tests.
type TriggerTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskName      string                 `protobuf:"bytes,1,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerTaskRequest) Reset() {
	*x = TriggerTaskRequest{}
	mi := &file_mock_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerTaskRequest) ProtoMessage() {}

func (x *TriggerTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mock_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerTaskRequest.ProtoReflect.Descriptor instead.
func (*TriggerTaskRequest) Descriptor() ([]byte, []int) {
	return file_mock_proto_rawDescGZIP(), []int{3}
}

func (x *TriggerTaskRequest) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

type InterruptCoopExitRequest struct {
	state          protoimpl.MessageState                           `protogen:"open.v1"`
	Action         InterruptCoopExitRequest_InterruptCoopExitAction `protobuf:"varint,1,opt,name=action,proto3,enum=mock.InterruptCoopExitRequest_InterruptCoopExitAction" json:"action,omitempty"`
	TargetOperator string                                           `protobuf:"bytes,2,opt,name=target_operator,json=targetOperator,proto3" json:"target_operator,omitempty"` // optional, defaults to MockAction.TargetOperatorID
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InterruptCoopExitRequest) Reset() {
	*x = InterruptCoopExitRequest{}
	mi := &file_mock_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterruptCoopExitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterruptCoopExitRequest) ProtoMessage() {}

func (x *InterruptCoopExitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mock_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterruptCoopExitRequest.ProtoReflect.Descriptor instead.
func (*InterruptCoopExitRequest) Descriptor() ([]byte, []int) {
	return file_mock_proto_rawDescGZIP(), []int{4}
}

func (x *InterruptCoopExitRequest) GetAction() InterruptCoopExitRequest_InterruptCoopExitAction {
	if x != nil {
		return x.Action
	}
	return InterruptCoopExitRequest_NONE
}

func (x *InterruptCoopExitRequest) GetTargetOperator() string {
	if x != nil {
		return x.TargetOperator
	}
	return ""
}

var File_mock_proto protoreflect.FileDescriptor

const file_mock_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"mock.proto\x12\x04mock\x1a\x1bgoogle/protobuf/empty.proto\"@\n" +
	"\x1bCleanUpPreimageShareRequest\x12!\n" +
	"\fpayment_hash\x18\x01 \x01(\fR\vpaymentHash\"\xaa\x01\n" +
	"\x18InterruptTransferRequest\x12N\n" +
	"\x06action\x18\x01 \x01(\x0e26.mock.InterruptTransferRequest.InterruptTransferActionR\x06action\">\n" +
	"\x17InterruptTransferAction\x12\b\n" +
	"\x04NONE\x10\x00\x12\r\n" +
	"\tINTERRUPT\x10\x01\x12\n" +
	"\n" +
	"\x06RESUME\x10\x02\"M\n" +
	"\x18UpdateNodesStatusRequest\x12\x19\n" +
	"\bnode_ids\x18\x01 \x03(\tR\anodeIds\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"1\n" +
	"\x12TriggerTaskRequest\x12\x1b\n" +
	"\ttask_name\x18\x01 \x01(\tR\btaskName\"\xd3\x01\n" +
	"\x18InterruptCoopExitRequest\x12N\n" +
	"\x06action\x18\x01 \x01(\x0e26.mock.InterruptCoopExitRequest.InterruptCoopExitActionR\x06action\x12'\n" +
	"\x0ftarget_operator\x18\x02 \x01(\tR\x0etargetOperator\">\n" +
	"\x17InterruptCoopExitAction\x12\b\n" +
	"\x04NONE\x10\x00\x12\r\n" +
	"\tINTERRUPT\x10\x01\x12\n" +
	"\n" +
	"\x06RESUME\x10\x022\x9b\x03\n" +
	"\vMockService\x12V\n" +
	"\x17clean_up_preimage_share\x12!.mock.CleanUpPreimageShareRequest\x1a\x16.google.protobuf.Empty\"\x00\x12N\n" +
	"\x12interrupt_transfer\x12\x1e.mock.InterruptTransferRequest\x1a\x16.google.protobuf.Empty\"\x00\x12O\n" +
	"\x13interrupt_coop_exit\x12\x1e.mock.InterruptCoopExitRequest\x1a\x16.google.protobuf.Empty\"\x00\x12O\n" +
	"\x13update_nodes_status\x12\x1e.mock.UpdateNodesStatusRequest\x1a\x16.google.protobuf.Empty\"\x00\x12B\n" +
	"\ftrigger_task\x12\x18.mock.TriggerTaskRequest\x1a\x16.google.protobuf.Empty\"\x00B+Z)github.com/lightsparkdev/spark/proto/mockb\x06proto3"

var (
	file_mock_proto_rawDescOnce sync.Once
	file_mock_proto_rawDescData []byte
)

func file_mock_proto_rawDescGZIP() []byte {
	file_mock_proto_rawDescOnce.Do(func() {
		file_mock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mock_proto_rawDesc), len(file_mock_proto_rawDesc)))
	})
	return file_mock_proto_rawDescData
}

var file_mock_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_mock_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_mock_proto_goTypes = []any{
	(InterruptTransferRequest_InterruptTransferAction)(0), // 0: mock.InterruptTransferRequest.InterruptTransferAction
	(InterruptCoopExitRequest_InterruptCoopExitAction)(0), // 1: mock.InterruptCoopExitRequest.InterruptCoopExitAction
	(*CleanUpPreimageShareRequest)(nil),                   // 2: mock.CleanUpPreimageShareRequest
	(*InterruptTransferRequest)(nil),                      // 3: mock.InterruptTransferRequest
	(*UpdateNodesStatusRequest)(nil),                      // 4: mock.UpdateNodesStatusRequest
	(*TriggerTaskRequest)(nil),                            // 5: mock.TriggerTaskRequest
	(*InterruptCoopExitRequest)(nil),                      // 6: mock.InterruptCoopExitRequest
	(*emptypb.Empty)(nil),                                 // 7: google.protobuf.Empty
}
var file_mock_proto_depIdxs = []int32{
	0, // 0: mock.InterruptTransferRequest.action:type_name -> mock.InterruptTransferRequest.InterruptTransferAction
	1, // 1: mock.InterruptCoopExitRequest.action:type_name -> mock.InterruptCoopExitRequest.InterruptCoopExitAction
	2, // 2: mock.MockService.clean_up_preimage_share:input_type -> mock.CleanUpPreimageShareRequest
	3, // 3: mock.MockService.interrupt_transfer:input_type -> mock.InterruptTransferRequest
	6, // 4: mock.MockService.interrupt_coop_exit:input_type -> mock.InterruptCoopExitRequest
	4, // 5: mock.MockService.update_nodes_status:input_type -> mock.UpdateNodesStatusRequest
	5, // 6: mock.MockService.trigger_task:input_type -> mock.TriggerTaskRequest
	7, // 7: mock.MockService.clean_up_preimage_share:output_type -> google.protobuf.Empty
	7, // 8: mock.MockService.interrupt_transfer:output_type -> google.protobuf.Empty
	7, // 9: mock.MockService.interrupt_coop_exit:output_type -> google.protobuf.Empty
	7, // 10: mock.MockService.update_nodes_status:output_type -> google.protobuf.Empty
	7, // 11: mock.MockService.trigger_task:output_type -> google.protobuf.Empty
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_mock_proto_init() }
func file_mock_proto_init() {
	if File_mock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mock_proto_rawDesc), len(file_mock_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mock_proto_goTypes,
		DependencyIndexes: file_mock_proto_depIdxs,
		EnumInfos:         file_mock_proto_enumTypes,
		MessageInfos:      file_mock_proto_msgTypes,
	}.Build()
	File_mock_proto = out.File
	file_mock_proto_goTypes = nil
	file_mock_proto_depIdxs = nil
}
